# Generated by Django 3.1.1 on 2020-12-14 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('postedon', models.DateTimeField()),
                ('rent', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('Insurance', models.BooleanField(default=True)),
                ('dents', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
