# Generated by Django 3.1.1 on 2020-12-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
