# Generated by Django 3.1.1 on 2020-12-14 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('no_plate', models.CharField(max_length=50)),
                ('posted_on', models.DateTimeField()),
                ('image', models.URLField(default=None)),
                ('rent', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('insurance', models.BooleanField(default=True)),
                ('dents', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
