# Generated by Django 3.1.1 on 2020-12-17 01:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_car_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
