# Generated by Django 3.1.1 on 2021-01-24 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_car_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='renter_wish',
            field=models.ManyToManyField(blank=True, related_name='asked_for_rent', to=settings.AUTH_USER_MODEL),
        ),
    ]
