# Generated by Django 3.1.1 on 2021-03-02 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210124_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='current_renter',
            field=models.ManyToManyField(blank=True, related_name='currenly_rented', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='past_renters',
            field=models.ManyToManyField(blank=True, related_name='rented', to=settings.AUTH_USER_MODEL),
        ),
    ]
