# Generated by Django 3.1.1 on 2021-03-20 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20210302_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_rent', models.DateTimeField()),
                ('time_of_endrent', models.DateTimeField(blank=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersRentedSoFar', to='network.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carsRentedSoFar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
