# Generated by Django 3.1.1 on 2021-03-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='curr_time_rent',
            field=models.DateTimeField(null=True),
        ),
    ]
