# Generated by Django 3.1.1 on 2021-03-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_car_curr_time_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='past_renters',
        ),
    ]
